// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoEAVmM23Dls3H5jeUp019Rx9X5fLdWm4',
    appId: '1:219793038613:web:fee6b1e769d2c434ad9d1c',
    messagingSenderId: '219793038613',
    projectId: 'cafem-5f88c',
    authDomain: 'cafem-5f88c.firebaseapp.com',
    storageBucket: 'cafem-5f88c.appspot.com',
    measurementId: 'G-Y4ZKCQJMXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtnsQALwmcW3vVRCe1XWJb53SaMHVyZIg',
    appId: '1:219793038613:android:d43189b5f56487ccad9d1c',
    messagingSenderId: '219793038613',
    projectId: 'cafem-5f88c',
    storageBucket: 'cafem-5f88c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5w5npW_QGYh2cEWbuc6kZhqAsBKZmEo',
    appId: '1:219793038613:ios:410effb6b167ab99ad9d1c',
    messagingSenderId: '219793038613',
    projectId: 'cafem-5f88c',
    storageBucket: 'cafem-5f88c.appspot.com',
    iosBundleId: 'com.example.cafem2',
  );
}
